
const EFFECTS: string[] = [
    "UncomfortableSleep",
    "Sleep",
    "NarcolepticSleep",
    "RestfulSleep",
    "AnewHope",
    "Mourning",
    "DisturbedSleep",
    "NewCrewArrival",
    "UnderWater",
    "FullBladder",
    "StressfulyEmptyingBladder",
    "RedAlert",
    "MentalBreak",
    "CoolingDown",
    "WarmingUp",
    "Darkness",
    "SteppedInContaminatedWater",
    "WellFed",
    "StaleFood",
    "SmelledPutridOdour",
    "Vomiting",
    "DirtyHands",
    "Unclean",
    "LightWounds",
    "ModerateWounds",
    "SevereWounds",
    "WasAttacked",
    "SoreBack",
    "WarmAir",
    "ColdAir",
    "Hypothermia",
    "Hyperthermia"
];
export default EFFECTS;